### ISSUE TITLE
Pretrained RetinexNet weights

### ISSUE THREAD

**Issue by mchan-sony** [ZPDu/DAI-Net#10]
Thanks for the great work! I was wondering whether you could share the pretrained RetinexNet weights that you used in your paper.

**Comment by ZPDu** [comment]
Hi, thanks for asking. I have uploaded the weight

**Comment by mchan-sony** [comment]
Thanks! It looks like the Google Drive link requires permission to download the weights. I've requested access to the link in the meantime.

**Comment by ZPDu** [comment]
Sorry for the mistake. I've made them all public

**Comment by mchan-sony** [comment]
Thank you so much!
