### ISSUE TITLE
yolov3

### ISSUE THREAD

**Issue by zhou-linkai** [ZPDu/DAI-Net#12]
Hello, is the code of yolov3 as the backbone network open source?

**Comment by ZPDu** [comment]
Hi, the code of yolov3 pipeline is not provided because our implementation is largely based on [MAET](https://github.com/cuiziteng/ICCV_MAET). The only modification is to adapt our reflectance decoder and proposed losses into their code.

**Comment by ZPDu** [comment]
Hi, I initially organized my code and released the implementation of DAI-Net with YOLO. Thank you for your patience
