### ISSUE TITLE
combination with yolo

### ISSUE THREAD

**Issue by CaipingPeng** [ZPDu/DAI-Net#14]
bro, How can insert your model into yolo network? can you help me?super thanks

**Comment by ZPDu** [comment]
Hi there, please check the implementation [here](https://github.com/cuiziteng/ICCV_MAET/blob/master/mmdet/models/roi_heads/shared_heads/aet_head.py). We inject the ref head in the same way as aet head. And we implement DAI-Net as [MAET-YOLO](https://github.com/cuiziteng/ICCV_MAET/blob/master/mmdet/models/detectors/MAET_YOLO/MAET_YOLO.py). I'll try to clean my code and release these files to help with the reproduction.

**Comment by Karthikps84** [comment]
Hello 
Thank you for your great work. When can you release this implementation part as it is very helpful?

**Comment by ZPDu** [comment]
Hi, I initially organized my code and released the implementation of DAI-Net with YOLO. Thank you
