### ISSUE TITLE
How to run darkface test while the competition was closed

### ISSUE THREAD

**Issue by 225ceV** [ZPDu/DAI-Net#15]
![image](https://github.com/user-attachments/assets/a0567e8e-70b4-4e72-9fb1-9e07b394ec75)

I am working on reproducing this project, but I find it impossible to submit results on codalab. I got stuck in the testing session because I couldn't find the submit guide on the web page. It just shows that the competition is over. I am new to codalab and would appreciate it if anyone could help me.

In addition, I found an evaluation program on the darkface website. I'm not sure if it will work. There are discussions about needing gt files and I don't know where to get them. I also had no experience with docker. I installed it in wsl2 and followed the instructions to test it.
```
sudo docker run --rm -it \
    -v /home/jjk/workspace/DAI-Net/result/test.run:/tools/data \
    -v /home/jjk/workspace/DAI-Net/result/finalres:/tools/output \
    scaffrey/eval_tools YOUR_ALGORITHM_NAME ./data/gt/ /root/UG2/Sub_challenge2_1/output/userid/output/submission_#/

```
I store the boxes generated by the detector in the 'test.run' folder and expect the results to be output to the 'finalres' folder.
but i got error:
```
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
error: textscan: invalid stream number = -1
error: called from
    df_eval at line 15 column 11
```
Has anyone successfully completed the test now? Could you give me some advice? I would appreciate it very much.

**Comment by ZPDu** [comment]
Hi there, thanks for reaching out. Could you try this [website](https://codalab.lisn.upsaclay.fr/) instead? After participating in the competition, you could find the submission samples under this page:
![image](https://github.com/user-attachments/assets/44641c0c-b668-462f-9aad-81dbc6f1e2e7)
And to submit results, please try this:
![image](https://github.com/user-attachments/assets/456dad92-a08d-4823-8e37-5098334b8304)

**Comment by 225ceV** [comment]
Thank you. I found the website. It works. But I still have some preblem.
It looks like the 100 images were used for Dry-run, which is no longer working. I put a zip of 100 txt files as submission and clicked the submit button and nothing happened except that the button darkened. I don't know if I did the right thing.
So submission is a zip of the results of a test run with 4000 images. Can we still run the results of dry-run100 images now?
I know this is a silly question, but I am new to codalab and just wanted to quickly check the results of ZS training.

**Comment by 225ceV** [comment]
Thank you. I found the website. It works. But I ran into some new problems.
It looks like the 100 images were used for Dry-run, which is no longer working. I put a zip of 100 txt files as submission and clicked the submit button and nothing happened except that the button darkened. I don't know if I did the right thing.
So submission is a zip of the results of a test run with 4000 images. Can we still run the results of dry-run100 images now?
I know this is a silly question, but I am new to codalab and just wanted to quickly check the results of ZS training.

**Comment by ZPDu** [comment]
Hi there, I didn't try the dry-run samples but I think the benchmarking is for the entire test set. The darkened button means that the results are being uploaded. All you need to do is to stay and wait for it to end. Later you could refresh the page and see that the results are successfully uploaded and being evalauted.
