### ISSUE TITLE
Implementation of DAINET with YOLO model

### ISSUE THREAD

**Issue by Karthikps84** [ZPDu/DAI-Net#16]
Hello
Thank you for your great work. When can you release this implementation part of DAINET with the YOLO model? such that we can reproduce the results.

**Comment by ZPDu** [comment]
Hi, thanks for reaching out! I’m currently busy with some other projects, and plan to work on releasing the implementation of DAI-Net with YOLO at a later time. I’ll keep you updated once it’s available.

**Comment by ZPDu** [comment]
I'm closing this issue since you've opened a new issue with the same request. I'll post response there.
