### ISSUE TITLE
Regarding the issue of training logs.

### ISSUE THREAD

**Issue by BAI-WQ** [ZPDu/DAI-Net#18]
Hello, author! Thank you very much for your outstanding work. I am very interested in your project! However, when I started training for reproducing low-light face detection on WiderFace--DarkFace, I noticed that no logs were generated. After reading the source code, I couldn't figure out the issue, as the map function was not defined. Could you please advise me on how to handle this part? I would appreciate your help

**Comment by ZPDu** [comment]
Hi, thanks for your interest. Could you elaborate on the training logs that you need? If loss logs are needed, you can simply add a SummaryWriter to the code.

**Comment by BAI-WQ** [comment]
Thank you for your response!I followed the instructions in your README file to run the program, but it didn’t generate the corresponding training.log. Everything else runs fine, except for the absence of the training.log. I am working on face detection, and I noticed that in your code the mAP calculation is not included—do I need to add it manually!By the way, could you let me know which GPU you used to run the program?
![微信截图_20241030192746](https://github.com/user-attachments/assets/e647f18b-c684-4357-9e73-aeb8e77fbbcb)

**Comment by ZPDu** [comment]
Thanks for your reply. As I recall, we didn’t calculate mAP during the training of face detection. Instead, we used the validation loss to monitor the model’s performance and selected the best-performing one for testing.

**Comment by BAI-WQ** [comment]
Alright, could you let me know why the training.log file isn’t generated when I run the program? Does the code above need any adjustments?

**Comment by ZPDu** [comment]
The code looks fine to me. I would suggest specifying an absolute file path or closing the logging file to force it to write. Alternatively, you could start with a toy example to ensure the logging works first.

**Comment by ZPDu** [comment]
And also notice that you have a '、' after 'losses += loss.item()'. Maybe checking the code again could help

**Comment by BAI-WQ** [comment]
Thank you for your advise， I will try it！！！
