### ISSUE TITLE
About pre-training weights

### ISSUE THREAD

**Issue by zzxf123** [ZPDu/DAI-Net#6]
Can you provide the pre-training weights (based on MAET) of coco on the Exdark dataset？ I want to train my data, thanks

**Comment by ZPDu** [comment]
Hi, model weight on ExDark is released

**Comment by zzxf123** [comment]
> Hi, model weight on MAET is released

Thanks I want to train my dataset, can you provide the pre-trained model of coco, which is the model before fine-tuning (load_from)

**Comment by ZPDu** [comment]
Hi there, I've checked but unfortunately I don't have the intermediate checkpoint after my internship ends

**Comment by zzxf123** [comment]
> Hi there, I've checked but unfortunately I don't have the intermediate checkpoint after my internship ends

thanks！
